### PR TITLE
Sept 9: Git part 2

### PR DESCRIPTION
**Pull request by thnguyn2**
Edited my readme.md file

### CODE REVIEW

**Comment by aaronta** [comment]
When could you do the machine learning this semester?

We meet every other Wed (opposite CSE seminars) from today (Jan 20) to April 27 and May 4.

**Comment by thnguyn2** [comment]
Hei man,
I will probably do it some time in March. I have a few travel plans over Feb. Any topics of interest?

**Comment by aaronta** [comment]
You mentioned machine learning. That would be great or anything you use regularly (e.g. LaTeX, Matlab, R, Python, plotting software, ....)

Just let me know what topic you decide on and which day.

Thanks!

**Comment by thnguyn2** [comment]
Ok, I will probably choose a simple machine learning tool in Python to do it. I will let you know ahead of time.

**Pull request merged**
